CREATE TABLE IF NOT EXISTS users (
	id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name      VARCHAR(255) NOT NULL,
	email     VARCHAR(255) NOT NULL,
	password  VARCHAR(72) NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX idx_users_email ON users (email);