CREATE TABLE IF NOT EXISTS users (
	id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name      VARCHAR(255) NOT NULL,
	email     VARCHAR(255) NOT NULL,
	password  VARCHAR(255) NOT NULL,
	created_at TIMESTAMPZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPZ DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMPZ DEFAULT NULL
);

CREATE INDEX idx_users_email ON users (email);