// Code generated by mockery v2.53.6. DO NOT EDIT.

package authmocks

import (
	auth "chuongpl/quan-ly-chi-tieu/internal/feature/auth"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	user "chuongpl/quan-ly-chi-tieu/internal/feature/user"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, req
func (_m *MockService) Login(ctx context.Context, req auth.LoginRequest) (*auth.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginRequest) (*auth.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginRequest) *auth.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.LoginRequest
func (_e *MockService_Expecter) Login(ctx interface{}, req interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockService_Login_Call) Run(run func(ctx context.Context, req auth.LoginRequest)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.LoginRequest))
	})
	return _c
}

func (_c *MockService_Login_Call) Return(_a0 *auth.AuthResponse, _a1 error) *MockService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(context.Context, auth.LoginRequest) (*auth.AuthResponse, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, jti, ttl
func (_m *MockService) Logout(ctx context.Context, jti string, ttl time.Duration) error {
	ret := _m.Called(ctx, jti, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, jti, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttl time.Duration
func (_e *MockService_Expecter) Logout(ctx interface{}, jti interface{}, ttl interface{}) *MockService_Logout_Call {
	return &MockService_Logout_Call{Call: _e.mock.On("Logout", ctx, jti, ttl)}
}

func (_c *MockService_Logout_Call) Run(run func(ctx context.Context, jti string, ttl time.Duration)) *MockService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockService_Logout_Call) Return(_a0 error) *MockService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Logout_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockService) RefreshToken(ctx context.Context, refreshToken string) (*auth.AuthResponse, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *auth.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.AuthResponse, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.AuthResponse); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockService_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockService_RefreshToken_Call {
	return &MockService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_RefreshToken_Call) Return(_a0 *auth.AuthResponse, _a1 error) *MockService_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (*auth.AuthResponse, error)) *MockService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockService) Register(ctx context.Context, req auth.RegisterRequest) (*user.UserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *user.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.RegisterRequest) (*user.UserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.RegisterRequest) *user.UserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.RegisterRequest
func (_e *MockService_Expecter) Register(ctx interface{}, req interface{}) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, req auth.RegisterRequest)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.RegisterRequest))
	})
	return _c
}

func (_c *MockService_Register_Call) Return(_a0 *user.UserResponse, _a1 error) *MockService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(context.Context, auth.RegisterRequest) (*user.UserResponse, error)) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
