// Code generated by mockery v2.53.6. DO NOT EDIT.

package usermocks

import (
	pkg "chuongpl/quan-ly-chi-tieu/internal/pkg"
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "chuongpl/quan-ly-chi-tieu/internal/feature/user"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockService) Create(ctx context.Context, _a1 *user.User) (*user.UserResponse, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *user.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) (*user.UserResponse, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) *user.UserResponse); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.User) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *user.User
func (_e *MockService_Expecter) Create(ctx interface{}, _a1 interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, _a1 *user.User)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.User))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *user.UserResponse, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, *user.User) (*user.UserResponse, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID
func (_m *MockService) Delete(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) Delete(ctx interface{}, userID interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: ctx, page, pageSize
func (_m *MockService) GetAllUsers(ctx context.Context, page int, pageSize int) ([]*user.UserResponse, *pkg.PaginationMeta, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*user.UserResponse
	var r1 *pkg.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*user.UserResponse, *pkg.PaginationMeta, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*user.UserResponse); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*user.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) *pkg.PaginationMeta); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pkg.PaginationMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockService_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockService_Expecter) GetAllUsers(ctx interface{}, page interface{}, pageSize interface{}) *MockService_GetAllUsers_Call {
	return &MockService_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, page, pageSize)}
}

func (_c *MockService_GetAllUsers_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockService_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockService_GetAllUsers_Call) Return(_a0 []*user.UserResponse, _a1 *pkg.PaginationMeta, _a2 error) *MockService_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_GetAllUsers_Call) RunAndReturn(run func(context.Context, int, int) ([]*user.UserResponse, *pkg.PaginationMeta, error)) *MockService_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmailAndDeletedAtIsNull provides a mock function with given fields: ctx, email
func (_m *MockService) GetByEmailAndDeletedAtIsNull(ctx context.Context, email string) (*user.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmailAndDeletedAtIsNull")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByEmailAndDeletedAtIsNull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmailAndDeletedAtIsNull'
type MockService_GetByEmailAndDeletedAtIsNull_Call struct {
	*mock.Call
}

// GetByEmailAndDeletedAtIsNull is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockService_Expecter) GetByEmailAndDeletedAtIsNull(ctx interface{}, email interface{}) *MockService_GetByEmailAndDeletedAtIsNull_Call {
	return &MockService_GetByEmailAndDeletedAtIsNull_Call{Call: _e.mock.On("GetByEmailAndDeletedAtIsNull", ctx, email)}
}

func (_c *MockService_GetByEmailAndDeletedAtIsNull_Call) Run(run func(ctx context.Context, email string)) *MockService_GetByEmailAndDeletedAtIsNull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetByEmailAndDeletedAtIsNull_Call) Return(_a0 *user.User, _a1 error) *MockService_GetByEmailAndDeletedAtIsNull_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByEmailAndDeletedAtIsNull_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *MockService_GetByEmailAndDeletedAtIsNull_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *MockService) GetByID(ctx context.Context, userID uuid.UUID) (*user.UserResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*user.UserResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *user.UserResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) GetByID(ctx interface{}, userID interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(_a0 *user.UserResponse, _a1 error) *MockService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*user.UserResponse, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, req
func (_m *MockService) Update(ctx context.Context, userID uuid.UUID, req user.UpdateUserRequest) (*user.UserResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *user.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, user.UpdateUserRequest) (*user.UserResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, user.UpdateUserRequest) *user.UserResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, user.UpdateUserRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req user.UpdateUserRequest
func (_e *MockService_Expecter) Update(ctx interface{}, userID interface{}, req interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, userID, req)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, req user.UpdateUserRequest)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(user.UpdateUserRequest))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *user.UserResponse, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, user.UpdateUserRequest) (*user.UserResponse, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
